'use strict';

const fs = require('fs');
const path = require('path');

const score = (val) => (val == null ? null : Math.round(val * 100));

const scoreIcon = (s) => {
  if (s == null) return '⚪';
  if (s >= 90) return '🟢';
  if (s >= 70) return '🟡';
  return '🔴';
};

const ms = (val) => (val == null ? '-' : `${Math.round(val)} ms`);
const cls = (val) => (val == null ? '-' : val.toFixed(3));

const readLhrs = (outputDir, core) => {
  try {
    const manifestPath = path.join(outputDir, 'manifest.json');
    core.info(`Reading manifest: ${manifestPath}`);
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    core.info(`Manifest entries: ${manifest.length}, representative: ${manifest.filter((e) => e.isRepresentativeRun).length}`);
    return manifest.map((entry) => {
      const jsonPath = path.isAbsolute(entry.jsonPath)
        ? entry.jsonPath
        : path.join(outputDir, entry.jsonPath);
      core.info(`Reading LHR: ${jsonPath}`);
      const lhr = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
      return { url: entry.url, lhr };
    });
  } catch (e) {
    core.warning(`Failed to read LHRs from ${outputDir}: ${e.message}`);
    return [];
  }
};

const formatUrlPath = (url) => {
  try {
    return new URL(url).pathname || '/';
  } catch {
    return url;
  }
};

const formatAppTable = (appLabel, outputDir, core) => {
  const runs = readLhrs(outputDir, core);

  if (!runs.length) {
    return `<details>\n<summary>${appLabel} — ⚠️ Lighthouse 결과를 불러오지 못했습니다.</summary>\n\n결과 없음\n\n</details>`;
  }

  const rows = runs.map(({ url, lhr }) => {
    const perf = score(lhr.categories?.performance?.score);
    const a11y = score(lhr.categories?.accessibility?.score);
    const lcp = lhr.audits?.['largest-contentful-paint']?.numericValue;
    const clsVal = lhr.audits?.['cumulative-layout-shift']?.numericValue;
    const tbt = lhr.audits?.['total-blocking-time']?.numericValue;

    return `| \`${formatUrlPath(url)}\` | ${scoreIcon(perf)} ${perf ?? '-'} | ${scoreIcon(a11y)} ${a11y ?? '-'} | ${ms(lcp)} | ${cls(clsVal)} | ${ms(tbt)} |`;
  });

  const perfScores = runs
    .map(({ lhr }) => score(lhr.categories?.performance?.score))
    .filter((s) => s != null);
  const minPerf = perfScores.length ? Math.min(...perfScores) : null;
  const overallIcon = scoreIcon(minPerf);
  const summary = `${overallIcon} ${appLabel} — Performance 최저 ${minPerf ?? '-'}점`;

  return `<details open>
<summary>${summary}</summary>

| URL | Perf | A11y | LCP | CLS | TBT |
|-----|:----:|:----:|----:|----:|----:|
${rows.join('\n')}

</details>`;
};

module.exports = async ({ github, context, core }) => {
  core.info(`CWD: ${process.cwd()}`);
  const homepageTable = formatAppTable(
    'Homepage',
    path.join(process.cwd(), 'apps/homepage/.lighthouseci'),
    core
  );
  const recruitTable = formatAppTable(
    'Recruit',
    path.join(process.cwd(), 'apps/recruit/.lighthouseci'),
    core
  );

  const body = `## ⚡ Lighthouse CI 리포트

${homepageTable}

${recruitTable}

> 🟢 ≥ 90 · 🟡 ≥ 70 · 🔴 < 70 &nbsp;|&nbsp; Performance 70 미만은 경고이며 CI를 실패시키지 않습니다.

<sub>Generated by [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) — commit ${context.sha.slice(0, 7)}</sub>`;

  const comments = await github.paginate(github.rest.issues.listComments, {
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: context.issue.number,
  });

  const existing = comments.find(
    (c) =>
      c.user.login === 'github-actions[bot]' &&
      c.body.includes('⚡ Lighthouse CI 리포트')
  );

  if (existing) {
    await github.rest.issues.updateComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await github.rest.issues.createComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: context.issue.number,
      body,
    });
  }
};
